import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { config } from "@/config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	other: {
		"fc:frame": "vNext",
		"fc:frame:image": config.startImage,
		"fc:frame:button:1": "Request to Join",
		"fc:frame:button:1:action": "post",
		"fc:frame:button:1:target": "https://channel.pinatadrops.com/api/join",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
